export const mockUserData = {
  user: {
    lastName: 'Helllo ',
    active: 'true',
    loginCount: 336,
    isoLang: 'en_US',
    passwordValidity: '2023-10-11 15:12:46',
    creationDate: '2023-09-01 19:53:07',
    refID: '50685424',
    lang: 'en',
    accessiblePermissions: [
      'devonly',
      'OE',
      'SOE',
      'DOT',
      'Analytics',
      'Tech support',
      'AOM',
      'OM',
      'SMS CCMS Dumps',
      'Raw Data Dump',
      'ACCESSTEAM',
      'SOCIAL',
      'DCS',
      'MC_READ',
      'MC_GOODWILL_READ',
      'MC_WRITE',
      'LP',
      'MC_SEARCH',
      'MC_CUSTOMER_UPDATE',
      'MC_CIR_VIEW',
      'MC_CIR_UPDATE',
      'MC_GWR_VIEW',
      'MC_GWR_UPDATE',
      'MC_SETTINGS',
      'CAMP_CONF_ALL',
      'CAMP_CREATE',
      'CAMP_MSG_CREATE',
      'CAMP_MSG_APPROVE',
      'CAMP_COUPON_CREATE',
      'CAMP_REPORT_VIEW',
      'CAMP_LIST_CONF',
      'CAMP_MSG_TEMPLATE_DESIGN',
      'configure_actions',
      'view_coupon_series',
      'view_rule_campaign',
      'configure_coupon_series',
      'bounceback_campaign_auth',
      'MC_RESEND_COUPON',
      'command_center_admin',
      'finance',
      'ADMIN_ACCESS',
      'PII_MASK',
      'PII_MASK_NOT_REQUIRED',
      'ALL_MSG_APPROVE',
      'COUPON_MSG_APPROVE',
      'POINTS_MSG_APPROVE',
      'LIST_CSV_UPLOAD',
      'EXT_FACT_ACCESS',
      'CAMP_XENGAGE_SETTINGS',
      'AUDIENCE_MANAGER_UI_VIEW',
      'CAMPAIGNS_UI_VIEW',
      'INCENTIVES_UI_VIEW',
      'CREATIVES_UI_VIEW',
      'UNMASKED_OTP_VIEW',
      'MC_WRT_GWP_REQ',
      'MC_XCUTE_GWP_REQ',
      'MC_WRT_GWC_REQ',
      'MC_XCUTE_GWC_REQ',
      'MC_WRT_GROUP_GWP_REQ',
      'MC_XCUTE_GROUP_GWP_REQ',
      'MC_WRT_PII_DLT_REQ',
      'MC_XCUTE_PII_DLT_REQ',
      'MC_WRT_RTRO_TXN_REQ',
      'MC_XCUTE_RTRO_TXN_REQ',
      'MC_WRT_M_REALLOC_REQ',
      'MC_XCUTE_M_REALLOC_REQ',
      'MC_WRT_ACC_MERGE_REQ',
      'MC_XCUTE_ACC_MERGE_REQ',
      'MC_WRT_TXN_REQ',
      'MC_XCUTE_TXN_REQ',
      'MC_WRT_IDCHANGE_MBL_REQ',
      'MC_XCUTE_IDCHANGE_MBL_REQ',
      'MC_WRT_IDCHANGE_EML_REQ',
      'MC_XCUTE_IDCHANGE_EML_REQ',
      'MC_WRT_IDCHANGE_EXID_REQ',
      'MC_XCUTE_IDCHANGE_EXID_RE',
      'MC_OLD_GOODWILL_XCUTE',
      'MC_OLD_GOODWILL_WRT',
      'MC_OLD_CHANGE_ID_XCUTE',
      'MC_OLD_CHANGE_ID_WRT',
      'MC_OLD_MBL_REALLOC_XCUTE',
      'MC_OLD_MBL_REALLOC_WRT',
      'MC_OLD_ACC_MERGE_XCUTE',
      'MC_OLD_ACC_MERGE_WRT',
      'MC_VIEW_GWP_REQ',
      'MC_VIEW_GWC_REQ',
      'MC_VIEW_GROUP_GWP_REQ',
      'MC_VIEW_PII_DLT_REQ',
      'MC_VIEW_RTRO_TXN_REQ',
      'MC_VIEW_M_REALLOC_REQ',
      'MC_VIEW_ACC_MERGE_REQ',
      'MC_VIEW_TXN_REQ',
      'MC_VIEW_IDCHANGE_MBL_REQ',
      'MC_VIEW_IDCHANGE_EML_REQ',
      'MC_VIEW_IDCHANGE_EXID_REQ',
      'MC_ISSUE_NEW_CARD',
      'MC_EDIT_CUST_SUBSCRIPTION',
      'MC_UPDATE_CARD_NUMBER',
      'LOYALTY_UPDATE_PROGRAM',
      'LOYALTY_UPDATE_PROMOTION',
    ],
    orgName: 'Capillary Technologies',
    userRoles: {
      ORG: [
        {
          entityType: 'ORG',
          entityName: 'Capillary Technologies',
          role: 'SUPERUSER',
          entityId: 0,
          childEntities: [],
        },
      ],
    },
    isCapUser: true,
    loginName: 'abc@capillarytech.com',
    proxyOrgList: [
      {
        orgID: 50947,
        orgName: 'Abhishek Test12',
      },
      {
        orgID: 1231,
        orgName: 'CLIENT_MERGE&MERGE',
      },
      {
        orgID: 0,
        orgName: 'Capillary Technologies',
      },
      {
        orgID: 1685,
        orgName: 'Consistency',
      },
      {
        orgID: 50753,
        orgName: 'Enormity',
      },
      {
        orgID: 51226,
        orgName: 'Falansh_TestOrg',
      },
      {
        orgID: 50228,
        orgName: 'IRIS_TEST',
      },
      {
        orgID: 1445,
        orgName: 'KartikPromotionTest',
      },
      {
        orgID: 50191,
        orgName: 'MLP_Org',
      },
      {
        orgID: 51546,
        orgName: 'Milind_Test_org',
      },
      {
        orgID: 50793,
        orgName: 'Prateek_Test',
      },
      {
        orgID: 50915,
        orgName: 'PyApps_Automation_03',
      },
      {
        orgID: 50371,
        orgName: 'RR Restro',
      },
      {
        orgID: 50933,
        orgName: 'Rebooters',
      },
      {
        orgID: 50146,
        orgName: 'Reon_Data',
      },
      {
        orgID: 50672,
        orgName: 'Sahana_TestOrg',
      },
      {
        orgID: 50780,
        orgName: 'Shradha',
      },
      {
        orgID: 50781,
        orgName: 'Shradha1',
      },
      {
        orgID: 50969,
        orgName: 'Shradha_Org',
      },
      {
        orgID: 50389,
        orgName: 'Sourabh Test Org',
      },
      {
        orgID: 51580,
        orgName: 'StabilityTestOrg1',
      },
      {
        orgID: 50959,
        orgName: 'VidhiOrg',
      },
      {
        orgID: 50074,
        orgName: 'mobile push',
      },
      {
        orgID: 50180,
        orgName: 'reon_data_fnb',
      },
    ],
    attributes: {
      USERNAME: {
        value: 'abc@capillarytech.com',
        verified: 'true',
      },
    },
    aryaUserRoles: {
      ORG: [
        {
          entityType: 'ORG',
          entityName: 'Capillary Technologies',
          role: 'SUPERUSER',
          entityId: 0,
          childEntities: [],
        },
      ],
    },
    accessRoles: {
      OnlyDev: 467,
    },
    accessibleOUList: {},
    type: 'ADMIN_USER',
    adminUser: true,
    id: '233082',
    firstName: 'ABC',
    orgID: 0,
  },
  currentOrgDetails: {
    basicDetails: {
      fiscalYearStart: '',
      baseCountryCode: 'IN',
      maxSmsHour: 21,
      baseCurrencyIso: {
        label: 'QAR',
        symbol: '﷼',
      },
      valueSmsCredits: '',
      bulkSmsCredits: '',
      supportedLanguages: [
        {
          langId: 69,
          language: 'English',
          isoCode: 'en',
        },
      ],
      baseCurrencyName: 'Qatari riyal',
      name: 'Rebooters',
      baseLanguageIso: {
        lang: '',
        locale: '',
      },
      baseTimezoneIso: {
        label: 'Asia/Singapore',
        offset: '+08:00',
      },
      phone: '',
      baseCountryIso: {
        code: 'IN',
        name: 'India',
      },
      address: 'HSR Layout Sector 2',
      orgId: '50933',
      minSmsHour: 9,
      baseCurrencySymbol: '﷼',
      language: '',
      timezoneOffset: '+08:00',
      timezone: 'Asia/Singapore',
      isActive: 1,
      baseLangLocale: '',
    },
    senderDetails: 'Requested org is not found',
    accessibleFeatures: [
      'PROMO_ENGINE',
      'GIFT_CARDS',
      'LOYALTY_PROMOTION_ENABLED',
      'BADGES_UI_ENABLED',
      'CREATE_BADGE_ENABLED',
      'ENABLE_BADGE_BENEFITS',
      'ENABLE_REWARDS_CATALOG',
    ],
    orgLoyaltyV2Status: true,
    moduleDetails: [
      {
        code: 'intouchHomePage',
        displayOrder: 1,
        id: -1,
        name: 'HOME',
        namespace: 'intouchHomePage',
        url: '/home/ui',
        version: '1.0.0',
      },
      {
        id: 44,
        name: 'ENGAGE+',
        code: 'campaigns/ui/list',
        version: '1.0.0.1',
        namespace: 'campaign',
        displayOrder: 9,
        url: '/campaigns/ui/list',
      },
      {
        id: 45,
        name: 'LOYALTY+',
        code: 'loyalty/ui/',
        version: '1.0.0.1',
        namespace: 'loyalty/ui/',
        displayOrder: 6,
        url: '/loyalty/ui/',
      },
      {
        id: 39,
        name: 'MEMBER CARE',
        code: 'memberCare',
        version: '1.0.0.1',
        namespace: 'memberCare',
        displayOrder: 0,
        url: '/memberCare',
      },
      {
        id: 36,
        name: 'ENGAGE',
        code: 'campaigns/ui/list',
        version: '1.0.0.1',
        namespace: 'campaign',
        displayOrder: 9,
        url: '/campaigns/ui/list',
      },
    ],
  },
  roles: [
    {
      role: 'SUPERUSER',
      organizationId: 0,
      organizationName: 'Capillary Technologies',
    },
  ],
  displayName: 'abc@capillarytech.com',
  email: 'abc@capillarytech.com',
  status: 'active',
  id: 233082,
};

export const mockOrganizationData = {
  response: {
    status: {
      success: 'true',
      code: 200,
      message: 'Success',
    },
    organization: {
      id: '50672',
      name: 'Sahana_TestOrg',
      address: 'hrs layout',
      language: '',
      language_code: '',
      language_locale: '',
      currency: '',
      timezone_offset: '+05:30',
      timezone: 'Asia/Kolkata',
      min_sms_hour: '2',
      max_sms_hour: '21',
      logo: '',
      parent_id: '-1',
      org_type: 'STANDARD_ORG',
      website: '',
      country: 'India',
      country_code: 'IN',
      state: 'Karnataka',
      city: 'Bellary',
      locality: 'chopra katla',
      pincode: '560102',
      currencies: {
        base_currency: {
          symbol: '',
          label: '',
        },
        supported_currencies: {
          currency: [],
        },
      },
      timezones: {
        base_timezone: {
          label: 'America/New_York',
          offset: '-04:00',
        },
        supported_timezones: {
          timezone: [
            {
              label: 'Asia/Kolkata',
              offset: '+05:30',
            },
            {
              label: 'Asia/Tokyo',
              offset: '+09:00',
            },
            {
              label: 'Asia/Kuala_Lumpur',
              offset: '+08:00',
            },
          ],
        },
      },
      languages: {
        base_language: {
          lang: '',
          locale: '',
        },
        supported_languages: {
          language: [],
        },
      },
      countries: {
        base_country: {
          name: 'India',
          code: 'IN',
        },
        supported_countries: {
          country: [
            {
              name: 'India',
              code: 'IN',
            },
          ],
        },
      },
    },
  },
};
